
/* application */
const JAMBONES_NETWORK_CIDR = process.env.JAMBONES_NETWORK_CIDR
const JAMBONES_LOGLEVEL = process.env.JAMBONES_LOGLEVEL
const HTTP_PORT = process.env.HTTP_PORT

const JAMBONZ_TAGGED_INBOUND = process.env.JAMBONZ_TAGGED_INBOUND
const JAMBONES_INBOUND_ROUTE = process.env.JAMBONES_INBOUND_ROUTE
const JAMBONES_OUTBOUND_ROUTE = process.env.JAMBONES_OUTBOUND_ROUTE
const JAMBONES_PEER_NETWORK_CIDR = process.env.JAMBONES_PEER_NETWORK_CIDR
const DOCKER_BRIDGE_IP = process.env.DOCKER_BRIDGE_IP

/* k8s */
const K8S = process.env.K8S
const K8S_SBC_REGISTER_SERVICE_NAME = process.env.K8S_SBC_REGISTER_SERVICE_NAME
const K8S_SBC_OPTIONS_SERVICE_NAME = process.env.K8S_SBC_OPTIONS_SERVICE_NAME
const K8S_SBC_INBOUND_SERVICE_NAME = process.env.K8S_SBC_INBOUND_SERVICE_NAME
const K8S_SBC_OUTBOUND_SERVICE_NAME = process.env.K8S_SBC_OUTBOUND_SERVICE_NAME

module.exports = {
  JAMBONES_NETWORK_CIDR,
  JAMBONES_LOGLEVEL,
  HTTP_PORT,
  JAMBONZ_TAGGED_INBOUND,
  JAMBONES_INBOUND_ROUTE,
  JAMBONES_OUTBOUND_ROUTE,
  JAMBONES_PEER_NETWORK_CIDR,
  DOCKER_BRIDGE_IP,
  K8S,
  K8S_SBC_REGISTER_SERVICE_NAME,
  K8S_SBC_OPTIONS_SERVICE_NAME,
  K8S_SBC_INBOUND_SERVICE_NAME,
  K8S_SBC_OUTBOUND_SERVICE_NAME
};
